name: Build

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    if: github.repository_owner == 'hustlahusky'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          pull: true
          push: true
